const particleData={
electron:["NEGATIVE CHARGE","ইলেকট্রন","ইলেকট্রন পরমাণুর একটি মৌলিক কণিকা যার আধান ঋণাত্মক। আপেক্ষিক আধান −1 এবং আপেক্ষিক ভরকে শূন্য ধরা হয়।","LOCATION → নিউক্লিয়াসের বাইরে"],
proton:["POSITIVE CHARGE","প্রোটন","প্রোটন পরমাণুর একটি মৌলিক কণিকা যার আধান ধনাত্মক। আপেক্ষিক আধান +1 এবং আপেক্ষিক ভর 1 ধরা হয়।","LOCATION → নিউক্লিয়াস"],
neutron:["NO CHARGE","নিউট্রন","নিউট্রন পরমাণুর একটি মৌলিক কণিকা যার কোনো আধান নেই। আপেক্ষিক আধান 0 এবং আপেক্ষিক ভর 1 ধরা হয়।","LOCATION → নিউক্লিয়াস"]};
document.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-p]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const d=particleData[b.dataset.p];document.querySelector("#particleInfo").innerHTML=`<small>${d[0]}</small><h3>${d[1]}</h3><p>${d[2]}</p><b>${d[3]}</b>`});
const modelData={r:["1911","রাদারফোর্ডের পরমাণু মডেল","নিউক্লিয়াসকে কেন্দ্র করে ইলেকট্রন বিভিন্ন কক্ষপথে ঘুরছে—সৌরজগতের সঙ্গে তুলনা করে এই মডেলকে Solar System model বা Nuclear model বলা হয়.",["নিউক্লিয়াস অত্যন্ত ক্ষুদ্র।","পরমাণুর ভেতরের বেশির ভাগ স্থান ফাঁকা।","নিউক্লিয়াসে প্রোটন ও নিউট্রন থাকে।"]],b:["1913","বোর পরমাণু মডেল","ইলেকট্রন ইচ্ছামতো যেকোনো কক্ষপথে ঘুরতে পারে না; নির্দিষ্ট ব্যাসার্ধের অনুমোদিত বৃত্তাকার কক্ষপথ বা স্থির শক্তিস্তরে অবস্থান করে.",["স্থির কক্ষপথে ইলেকট্রন শক্তি শোষণ/বিকিরণ করে না।","n=1,2,3,4... প্রধান শক্তিস্তরকে নির্দেশ করে।","উচ্চ শক্তিস্তরে গেলে শক্তি শোষণ, নিচে এলে শক্তি বিকিরণ হয়।"]]};
document.querySelectorAll("[data-model]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-model]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const d=modelData[b.dataset.model];document.querySelector("#modelYear").textContent=d[0];document.querySelector("#modelTitle").textContent=d[1];document.querySelector("#modelText").textContent=d[2];document.querySelector("#modelPoints").innerHTML=d[3].map(x=>`<li>${x}</li>`).join("");document.querySelectorAll(".hidden").forEach(x=>x.classList.toggle("hidden",b.dataset.model!=="b"))});
const symbols=[null,"H","He","Li","Be","B","C","N","O","F","Ne","Na","Mg","Al","Si","P","S","Cl","Ar","K","Ca","Sc","Ti","V","Cr","Mn","Fe","Co","Ni","Cu","Zn"];
const names=[null,"Hydrogen","Helium","Lithium","Beryllium","Boron","Carbon","Nitrogen","Oxygen","Fluorine","Neon","Sodium","Magnesium","Aluminium","Silicon","Phosphorus","Sulfur","Chlorine","Argon","Potassium","Calcium","Scandium","Titanium","Vanadium","Chromium","Manganese","Iron","Cobalt","Nickel","Copper","Zinc"];
const configs={1:[1],2:[2],3:[2,1],4:[2,2],5:[2,3],6:[2,4],7:[2,5],8:[2,6],9:[2,7],10:[2,8],11:[2,8,1],12:[2,8,2],13:[2,8,3],14:[2,8,4],15:[2,8,5],16:[2,8,6],17:[2,8,7],18:[2,8,8],19:[2,8,8,1],20:[2,8,8,2],21:[2,8,9,2],22:[2,8,10,2],23:[2,8,11,2],24:[2,8,13,1],25:[2,8,13,2],26:[2,8,14,2],27:[2,8,15,2],28:[2,8,16,2],29:[2,8,18,1],30:[2,8,18,2]};
function renderConfig(z){document.querySelector("#zVal").value=z;document.querySelector("#elSymbol").textContent=symbols[z];document.querySelector("#elName").textContent=names[z];const c=configs[z];document.querySelector("#configReadout").textContent=c.join(", ");document.querySelector("#shells").innerHTML=c.map((n,i)=>`<div class="shell-view" style="width:${80+i*22}px;height:${80+i*22}px"><b>${n}</b><span>${["K","L","M","N"][i]||""}</span></div>`).join("")}
document.querySelector("#zSlider").oninput=e=>renderConfig(+e.target.value);renderConfig(11);
const avg=document.querySelector("#isoA");function calcAvg(){let x=+avg.value;document.querySelector("#avgOut").textContent=((63*x+65*(100-x))/100).toFixed(1)}avg.oninput=calcAvg;
document.querySelectorAll(".practice-card").forEach(card=>card.querySelectorAll("button").forEach(btn=>btn.onclick=()=>{const ok=btn.textContent.trim()===card.querySelector(".answers").dataset.correct;card.querySelector(".feedback").textContent=ok?"✓ Correct!":"Not quite — review the relevant section and try again.";card.querySelectorAll("button").forEach(x=>x.disabled=true)}));
const qs=[["পরমাণুর পারমাণবিক সংখ্যা কী নির্দেশ করে?",["প্রোটন সংখ্যা","নিউট্রন সংখ্যা","ভর সংখ্যা","শক্তিস্তর"],0],["A=23, Z=11 হলে নিউট্রন সংখ্যা কত?",["11","12","23","34"],1],["Bohr model-এর স্থির কক্ষপথে ইলেকট্রন কী করে?",["ক্রমাগত শক্তি হারায়","শক্তি শোষণ/বিকিরণ করে না","নিউক্লিয়াসে পড়ে যায়","চার্জ হারায়"],1],["N প্রধান শক্তিস্তরের n-এর মান কত?",["1","2","3","4"],3],["⁶³Cu 75% এবং ⁶⁵Cu 25% হলে গড় আপেক্ষিক পারমাণবিক ভর?",["62.5","63.5","64.5","65.5"],1],["H₂SO₄-এর আপেক্ষিক আণবিক ভর কত?",["49","64","98","100"],2]];
let qi=0,sc=0;function renderQ(){const q=qs[qi];document.querySelector("#qCount").textContent=`${qi+1} / ${qs.length}`;document.querySelector("#qBar").style.width=`${qi/qs.length*100}%`;document.querySelector("#qScore").textContent=`${sc} pts`;document.querySelector("#qText").textContent=q[0];document.querySelector("#qFeedback").textContent="";document.querySelector("#qAnswers").innerHTML=q[1].map((x,i)=>`<button data-i="${i}">${x}</button>`).join("");document.querySelectorAll("#qAnswers button").forEach(b=>b.onclick=()=>{if(+b.dataset.i===q[2]){sc++;document.querySelector("#qFeedback").textContent="✓ Correct!"}else document.querySelector("#qFeedback").textContent=`Correct answer: ${q[1][q[2]]}`;document.querySelectorAll("#qAnswers button").forEach(x=>x.disabled=true);setTimeout(()=>{qi++;if(qi<qs.length)renderQ();else{document.querySelector("#qCount").textContent="COMPLETE";document.querySelector("#qBar").style.width="100%";document.querySelector("#qText").textContent=`Score: ${sc} / ${qs.length}`;document.querySelector("#qAnswers").innerHTML='<button onclick="location.reload()">Restart</button>'}},550)})}renderQ();
